name: DelDropItems
version: 1.1.2
main: plugin.DelDropItems.Main
api-version: 1.12
commands:
  ddi:
    description: "Main command of the plugin."
    usage: "/ddi <subcommand>"
    aliases: [ "delDropItems" ]
    permission: "delDropItems.use"
    permission-message: "You do not have permission to use this command."
    subcommands:
      reload:
        description: "Reloads the plugin configuration."
        usage: "/ddi reload"
      help:
        description: "Displays the list of plugin commands."
        usage: "/ddi help"
permissions:
  delDropItems.reload:
    description: "Permission to reload the plugin configuration."
    default: op
  delDropItems.help:
    description: "Permission to view the plugin commands."
    default: op
  delDropItems.view-logs:
    description: "Permission to view item deletion logs"
    default: op
